name: Build Android AAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    name: Build Signed Android AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.0"
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get
